<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Insert extends MY_Controller {

    public function __construct()
    {
        parent::__construct();
    }

    // ニッポン放送(id:3)
    public function top()
    {
        $data = [
            [
                'program_name'       => 'あさぼらけ',
                'dir_name'           => 'lfrasaborake',
                'day_id'        => 8,
                'starttime'  => "5:00",
                'finishtime' => '6:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 1,
                'officialsite'       => 'https://www.1242.com/asaborake/',
                'mailaddress'        => 'ue@1242.com'
            ],
            [
                'program_name'       => "飯田浩司のOK!Cozy up!",
                'dir_name'           => 'lfrcozy',
                'day_id'        => 8,
                'starttime'  => "6:00",
                'finishtime' => '8:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 1,
                'officialsite'       => 'https://www.1242.com/cozy/',
                'mailaddress'        => 'cozy@1242.com'
            ],
            [
                'program_name'       => "あさナビ",
                'dir_name'           => 'lfrasanav',
                'day_id'        => 8,
                'starttime'  => "6:43",
                'finishtime' => '6:49',
                'broadcast_id'       => 3,
                'timezone_id'        => 1,
                'officialsite'       => 'https://www.1242.com/asanav/',
                'mailaddress'        => ''
            ],
            [
                'program_name'       => '羽田美智子のいってらっしゃい',
                'dir_name'           => 'lfrhada',
                'day_id'        => 8,
                'starttime'  => "7:37",
                'finishtime' => '7:42',
                'broadcast_id'       => 3,
                'timezone_id'        => 1,
                'officialsite'       => 'https://www.1242.com/hada/',
                'mailaddress'        => 'hada@1242.com'
            ],
            [
                'program_name'       => '垣花正あなたとハッピー!',
                'dir_name'           => 'tbsar',
                'day_id'        => 9,
                'starttime'  => "8:00",
                'finishtime' => '11:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 2,
                'officialsite'       => 'https://www.1242.com/happy/',
                'mailaddress'        => ''
            ],
            [
                'program_name'       => '川井郁子 ハートストリングス',
                'dir_name'           => 'tbskawai',
                'day_id'        => 8,
                'starttime'  => "8:25",
                'finishtime' => '8:28',
                'broadcast_id'       => 3,
                'timezone_id'        => 2,
                'officialsite'       => '',
                'mailaddress'        => ''
            ],
            [
                'program_name'       => '榊原郁恵のハッピー・ダイアリー',
                'dir_name'           => 'lfrikue',
                'day_id'        => 8,
                'starttime'  => "10:12",
                'finishtime' => '10:17',
                'broadcast_id'       => 3,
                'timezone_id'        => 2,
                'officialsite'       => 'https://www.1242.com/program/ikue/',
                'mailaddress'        => ''
            ],
            [
                'program_name'       => 'うつみ宮土理のおしゃべりしましょ',
                'dir_name'           => 'lfrkeronpa',
                'day_id'        => 8,
                'starttime'  => "10:35",
                'finishtime' => '10:40',
                'broadcast_id'       => 3,
                'timezone_id'        => 2,
                'officialsite'       => 'https://www.1242.com/radio/keronpa/',
                'mailaddress'        => 'keronpa@1242.com'
            ],
            [
                'program_name'       => 'テレフォン人生相談',
                'dir_name'           => 'lfrjinseisoudan',
                'day_id'        => 8,
                'starttime'  => "11:00",
                'finishtime' => '11:20',
                'broadcast_id'       => 3,
                'timezone_id'        => 2,
                'officialsite'       => 'https://www.1242.com/jinseisoudan/',
                'mailaddress'        => ''
            ],
            [
                'program_name'       => '高田文夫のラジオビバリー昼ズ',
                'dir_name'           => 'lfrtakada',
                'day_id'        => 8,
                'starttime'  => "11:30",
                'finishtime' => '13:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 2,
                'officialsite'       => 'https://www.1242.com/takada/',
                'mailaddress'        => 'https://www.1242.com/takada/'
            ],
            [
                'program_name'       => 'DAYS',
                'dir_name'           => 'lfrdays',
                'day_id'        => 12,
                'starttime'  => "13:00",
                'finishtime' => '16:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/days/',
                'mailaddress'        => 'https://www.1242.com/days/'
            ],
            [
                'program_name'       => '辛坊治郎 ズーム そこまで言うか！激論Rock&Go! ',
                'dir_name'           => 'lfrzoom',
                'day_id'        => 1,
                'starttime'  => "13:00",
                'finishtime' => '16:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.tbsradio.jp/miyari/',
                'mailaddress'        => 'zoom@1242.com'
            ],
            [
                'program_name'       => '大橋未歩 金曜ブラボー',
                'dir_name'           => 'lfrokb',
                'day_id'        => 5,
                'starttime'  => "13:00",
                'finishtime' => '17:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/okb/',
                'mailaddress'        => 'okb@1242.com'
            ],
            [
                'program_name'       => '草野満代 夕暮れWONDER4',
                'dir_name'           => 'lfrw4',
                'day_id'        => 9,
                'starttime'  => "16:00",
                'finishtime' => '18:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/w4/',
                'mailaddress'        => 'w4@1242.com'
            ],
            [
                'program_name'       => '有楽町930ステーション',
                'dir_name'           => 'lfr930',
                'day_id'        => 5,
                'starttime'  => "17:00",
                'finishtime' => '17:10',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => '',
                'mailaddress'        => '930@1242.com'
            ],
            [
                'program_name'       => '河北麻友子のマユコレ！',
                'dir_name'           => 'lfrmayuko',
                'day_id'        => 5,
                'starttime'  => "17:10",
                'finishtime' => '17:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/mayuko/',
                'mailaddress'        => 'mayuko@1242.com'
            ],
            [
                'program_name'       => 'フライデー ナイタースペシャル',
                'dir_name'           => 'lfrfocussp',
                'day_id'        => 3,
                'starttime'  => "17:30",
                'finishtime' => '21:20',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/focussp/',
                'mailaddress'        => '89@1242.com'
            ],
            [
                'program_name'       => '板東英二のプロ野球バンバン伝説',
                'dir_name'           => 'lfrban',
                'day_id'        => 1,
                'starttime'  => "18:00",
                'finishtime' => '18:20',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => '',
                'mailaddress'        => 'ban@1242.com'
            ],
            [
                'program_name'       => 'ガクのネ',
                'dir_name'           => 'lfrgakunone',
                'day_id'        => 1,
                'starttime'  => "18:20",
                'finishtime' => '18:40',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/gakunone/',
                'mailaddress'        => 'gakunone@1242.com'
            ],
            [
                'program_name'       => '大石久和のラジオ国土学入門',
                'dir_name'           => 'lfrkokudogaku',
                'day_id'        => 1,
                'starttime'  => "18:40",
                'finishtime' => '19:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/kokudogaku/',
                'mailaddress'        => 'kokudogaku@1242.com'
            ],
            [
                'program_name'       => 'GENERATIONS 小森隼のGood Laugh and Sleep',
                'dir_name'           => 'lfrsleep',
                'day_id'        => 1,
                'starttime'  => "19:00",
                'finishtime' => '19:20',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/komori_sleep/',
                'mailaddress'        => 'sleep@1242.com'
            ],
            [
                'program_name'       => '私の正論',
                'dir_name'           => 'lfrseiron',
                'day_id'        => 1,
                'starttime'  => "19:20",
                'finishtime' => '19:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/seiron/',
                'mailaddress'        => ''
            ],
            [
                'program_name'       => "KIREI NOTE Lounge",
                'dir_name'           => 'tbsdaikokai',
                'day_id'        => 1,
                'starttime'  => "19:30",
                'finishtime' => '20:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://twitter.com/kireinotelounge',
                'mailaddress'        => 'kirei@1242.com'
            ],
            [
                'program_name'       => '劇団EXILEのREPROFILE',
                'dir_name'           => 'lfrreprofile',
                'day_id'        => 1,
                'starttime'  => "20:00",
                'finishtime' => '20:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.allnightnippon.com/reprofile/',
                'mailaddress'        => 'rp@1242.com'
            ],
            [
                'program_name'       => 'RAISE A SUILENのRADIO R・I・O・T',
                'dir_name'           => 'lfrbang_dream',
                'day_id'        => 1,
                'starttime'  => "20:30",
                'finishtime' => '21:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/bang_dream/',
                'mailaddress'        => 'bdp@1242.com'
            ],
            [
                'program_name'       => 'ことばのチカラ ～成功へのターニングポイント～',
                'dir_name'           => 'lfrchikara',
                'day_id'        => 1,
                'starttime'  => "21:00",
                'finishtime' => '21:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/radio/chikara/',
                'mailaddress'        => ''
            ],
            [
                'program_name'       => '阿部亮のNGO世界一周！',
                'dir_name'           => 'tbstokyopod',
                'day_id'        => 1,
                'starttime'  => "21:30",
                'finishtime' => '21:50',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/radio/aberyo/?doing_wp_cron=1589973927.1107060909271240234375',
                'mailaddress'        => 'aberyo@1242.com'
            ],
            [
                'program_name'       => 'スポーツ伝説',
                'dir_name'           => 'lfrsports',
                'day_id'        => 8,
                'starttime'  => "21:50",
                'finishtime' => '21:57',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/sports/',
                'mailaddress'        => 'sd@1242.com'
            ],
            [
                'program_name'       => '看板娘ホッピー・ミーナのHOPPY HAPPY BAR',
                'dir_name'           => 'lfrhoppy',
                'day_id'        => 8,
                'starttime'  => "21:57",
                'finishtime' => '22:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/hoppy/',
                'mailaddress'        => 'hoppy@1242.com'
            ],
            [
                'program_name'       => 'オールナイトニッポン MUSIC10',
                'dir_name'           => 'lfrm10',
                'day_id'        => 9,
                'starttime'  => "22:00",
                'finishtime' => '24:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.allnightnippon.com/m10/',
                'mailaddress'        => '10@1242.com'
            ],
            [
                'program_name'       => 'ザ・フォーカス',
                'dir_name'           => 'lfrfocus',
                'day_id'        => 19,
                'starttime'  => "18:00",
                'finishtime' => '21:20',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/focus/',
                'mailaddress'        => 'focus@1242.com'
            ],
            [
                'program_name'       => 'ソードアート・オンエアー',
                'dir_name'           => 'lfrsao',
                'day_id'        => 4,
                'starttime'  => "21:20",
                'finishtime' => '21:40',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/sao/',
                'mailaddress'        => 'sao@1242.com'
            ],
            [
                'program_name'       => 'ラジオ新大陸',
                'dir_name'           => 'lfrtairiku',
                'day_id'        => 3,
                'starttime'  => "21:20",
                'finishtime' => '21:40',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/tairiku/',
                'mailaddress'        => 'tairiku@1242.com'
            ],
            [
                'program_name'       => 'BOUSAI LIGHT HOUSE',
                'dir_name'           => 'lfrhimawali',
                'day_id'        => 4,
                'starttime'  => "21:20",
                'finishtime' => '21:40',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/himawali/',
                'mailaddress'        => 'himawali@1242.com'
            ],
            [
                'program_name'       => '望月智之 イノベーターズ・クロス',
                'dir_name'           => 'lfrcross',
                'day_id'        => 5,
                'starttime'  => "21:20",
                'finishtime' => '21:40',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/cross/',
                'mailaddress'        => 'mochi@1242.com'
            ],
            [
                'program_name'       => '西川貴教のちょこっとナイトニッポン!',
                'dir_name'           => 'lfrnishikawa',
                'day_id'        => 10,
                'starttime'  => "21:40",
                'finishtime' => '21:50',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.allnightnippon.com/nishikawa/',
                'mailaddress'        => 'nishikawa@1242.com'
            ],
            [
                'program_name'       => 'オールナイトニッポンGOLD',
                'dir_name'           => 'lfrgold',
                'day_id'        => 5,
                'starttime'  => "22:00",
                'finishtime' => '24:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.allnightnippon.com/gold/',
                'mailaddress'        => ''
            ],
            [
                'program_name'       => 'ミューコミプラス',
                'dir_name'           => 'lfrmcplus',
                'day_id'        => 9,
                'starttime'  => "24:00",
                'finishtime' => '24:53',
                'broadcast_id'       => 3,
                'timezone_id'        => 5,
                'officialsite'       => 'https://www.allnightnippon.com/mcplus/',
                'mailaddress'        => 'mc@allnightnippon.com'
            ],
            [
                'program_name'       => '三代目 J SOUL BROTHERS 山下健二郎のZERO BASE',
                'dir_name'           => 'lfrykzb',
                'day_id'        => 5,
                'starttime'  => "24:00",
                'finishtime' => '25:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 5,
                'officialsite'       => 'https://www.allnightnippon.com/ykzb/',
                'mailaddress'        => 'yk@allnightnippon.com'
            ],
            [
                'program_name'       => '熊田茜音　アカネノ音',
                'dir_name'           => 'lfrakane',
                'day_id'        => 9,
                'starttime'  => "24:53",
                'finishtime' => '24:58',
                'broadcast_id'       => 3,
                'timezone_id'        => 5,
                'officialsite'       => 'https://www.allnightnippon.com/akane/',
                'mailaddress'        => 'akane@allnightnippon.com'
            ],
            [
                'program_name'       => '徳光和夫　とくモリ！歌謡サタデー',
                'dir_name'           => 'lfrtoku',
                'day_id'        => 6,
                'starttime'  => "5:00",
                'finishtime' => '7:40',
                'broadcast_id'       => 3,
                'timezone_id'        => 1,
                'officialsite'       => 'https://www.1242.com/toku/',
                'mailaddress'        => 'toku@1242.com'
            ],
            [
                'program_name'       => 'おしゃべりラボ〜しあわせSocial Design〜',
                'dir_name'           => 'lfrlab',
                'day_id'        => 6,
                'starttime'  => "7:40",
                'finishtime' => '8:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 1,
                'officialsite'       => '',
                'mailaddress'        => 'lab@1242.com'
            ],
            [
                'program_name'       => 'Music Machine GO! GO!☆',
                'dir_name'           => 'lfrmmgg',
                'day_id'        => 6,
                'starttime'  => "8:00",
                'finishtime' => '8:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 2,
                'officialsite'       => '',
                'mailaddress'        => 'katsuya@1242.com'
            ],
            [
                'program_name'       => 'LOVE & MELODY',
                'dir_name'           => 'lfrlove',
                'day_id'        => 6, 
                'starttime'  => "8:30",
                'finishtime' => '10:50',
                'broadcast_id'       => 3,
                'timezone_id'        => 2,
                'officialsite'       => 'https://www.1242.com/love/',
                'mailaddress'        => 'love@1242.com'
            ],
            [
                'program_name'       => 'キャイーンの家電ソムリエ',
                'dir_name'           => 'lfrsomme',
                'day_id'        => 6,
                'starttime'  => "10:50",
                'finishtime' => '11:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 2,
                'officialsite'       => 'https://kbc.co.jp/r-radio/kaden-sommelier/',
                'mailaddress'        => ''
            ],
            [
                'program_name'       => 'ゴッドアフタヌーン アッコのいいかげんに1000回',
                'dir_name'           => 'lfrakko',
                'day_id'        => 6,
                'starttime'  => "11:00",
                'finishtime' => '13:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 2,
                'officialsite'       => 'https://www.1242.com/akko/',
                'mailaddress'        => 'akko@1242.com'
            ],
            [
                'program_name'       => 'サタデーミュージックバトル 天野ひろゆき ルート930',
                'dir_name'           => 'lfrroute930',
                'day_id'        => 6,
                'starttime'  => "13:00",
                'finishtime' => '16:20',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/route930/',
                'mailaddress'        => 'r930@1242.com'
            ],
            [
                'program_name'       => '渡邉美樹 5年後の夢を語ろう!',
                'dir_name'           => 'lfryume5',
                'day_id'        => 6,
                'starttime'  => "16:20",
                'finishtime' => '16:50',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/yume5/',
                'mailaddress'        => 'yume5@1242.com'
            ],
            [
                'program_name'       => 'NOKKOのオカエリ ただいま。',
                'dir_name'           => 'lfrnokko',
                'day_id'        => 6,
                'starttime'  => "16:50",
                'finishtime' => '17:10',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/nokko/',
                'mailaddress'        => 'nokko@1242.com'
            ],
            [
                'program_name'       => "さまぁ〜ず三村マサカズと小島瑠璃子の「みむこじラジオ！」",
                'dir_name'           => 'lfrmk',
                'day_id'        => 6,
                'starttime'  => "17:10",
                'finishtime' => '17:40',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/radio/mk/',
                'mailaddress'        => 'mk@1242.com'
            ],
            [
                'program_name'       => '龍 真咲のMOONLIGHT PARTY',
                'dir_name'           => 'lfrmasaki',
                'day_id'        => 6,
                'starttime'  => "21:10",
                'finishtime' => '21:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/masaki/',
                'mailaddress'        => 'masaki@1242.com'
            ],
            [
                'program_name'       => "藤田ニコルのあしたはにちようび",
                'dir_name'           => 'tbsnico',
                'day_id'        => 6,
                'starttime'  => "19:00",
                'finishtime' => '20:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.tbsradio.jp/nico/',
                'mailaddress'        => 'nico@1242.com'
            ],
            [
                'program_name'       => '山崎育三郎のI AM 1936',
                'dir_name'           => 'lfr1936',
                'day_id'        => 6,
                'starttime'  => "21:30",
                'finishtime' => '22:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/radio/ikusaburo/',
                'mailaddress'        => '1936@1242.com'
            ],
            [
                'program_name'       => '鈴木亮平 Going Up',
                'dir_name'           => 'lfrgoingup',
                'day_id'        => 6,
                'starttime'  => "22:00",
                'finishtime' => '22:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/radio/goingup/',
                'mailaddress'        => 'go@1242.com'
            ],
            [
                'program_name'       => '藤ヶ谷太輔 Peaceful Days',
                'dir_name'           => 'lfrgaya',
                'day_id'        => 6,
                'starttime'  => "22:30",
                'finishtime' => '23:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/gaya/',
                'mailaddress'        => 'gaya@1242.com'
            ],
            [
                'program_name'       => '中居正広 ON & ON AIR',
                'dir_name'           => 'lfrnakai',
                'day_id'        => 6,
                'starttime'  => "23:00",
                'finishtime' => '23:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => '',
                'mailaddress'        => ''
            ],
            [
                'program_name'       => 'ひろたみゆ紀のサンデー早起き有楽町',
                'dir_name'           => 'lfrsunday',
                'day_id'        => 7,
                'starttime'  => "5:00",
                'finishtime' => '7:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 1,
                'officialsite'       => 'https://www.1242.com/radio/sunday/',
                'mailaddress'        => 'sunday@1242.com'
            ],
            [
                'program_name'       => '魔法のラジオ',
                'dir_name'           => 'lfrmahou',
                'day_id'        => 7,
                'starttime'  => "5:06",
                'finishtime' => '5:16',
                'broadcast_id'       => 3,
                'timezone_id'        => 1,
                'officialsite'       => 'https://www.1242.com/radio/mahou/',
                'mailaddress'        => 'mahou@1242.com'
            ],
            [
                'program_name'       => '中山秀征の有楽町で逢いまSHOW',
                'dir_name'           => 'lfrhide',
                'day_id'        => 7,
                'starttime'  => "5:30",
                'finishtime' => '6:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 1,
                'officialsite'       => 'https://www.1242.com/hide/',
                'mailaddress'        => 'hide@1242.com'
            ],
            [
                'program_name'       => 'すくすく育て 子どもの未来健康プロジェクト',
                'dir_name'           => 'lfrsukusuku',
                'day_id'        => 7,
                'starttime'  => "6:04",
                'finishtime' => '6:13',
                'broadcast_id'       => 3,
                'timezone_id'        => 1,
                'officialsite'       => 'https://www.1242.com/radio/sukusuku/',
                'mailaddress'        => 'jimi@1242.com'
            ],
            [
                'program_name'       => 'ウィークエンド・ケアタイム 「ひだまりハウス」 ～うつ病・認知症について語ろう～',
                'dir_name'           => 'lfrhidamari',
                'day_id'        => 7,
                'starttime'  => "6:25",
                'finishtime' => '6:54',
                'broadcast_id'       => 3,
                'timezone_id'        => 1,
                'officialsite'       => 'https://www.1242.com/hidamari/',
                'mailaddress'        => 'hidamari@1242.com'
            ],
            [
                'program_name'       => 'イルカのミュージックハーモニー',
                'dir_name'           => 'lfriruka',
                'day_id'        => 7,
                'starttime'  => "7:00",
                'finishtime' => '8:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 1,
                'officialsite'       => 'https://www.1242.com/radio/iruka/',
                'mailaddress'        => 'iruka@1242.com'
            ],
            [
                'program_name'       => '薬師丸ひろ子　ハート・デリバリー',
                'dir_name'           => 'lfrhiroko',
                'day_id'        => 7,
                'starttime'  => "8:30",
                'finishtime' => '9:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 2,
                'officialsite'       => '',
                'mailaddress'        => 'hiroko@1242.com'
            ],
            [
                'program_name'       => '三宅裕司 サンデーヒットパラダイス',
                'dir_name'           => 'lfrmiyake',
                'day_id'        => 7,
                'starttime'  => "9:00",
                'finishtime' => '12:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 2,
                'officialsite'       => 'https://www.1242.com/miyake/',
                'mailaddress'        => 'miyake@1242.com'
            ],
            [
                'program_name'       => '土田晃之 日曜のへそ',
                'dir_name'           => 'lfrtsuchida',
                'day_id'        => 7,
                'starttime'  => "12:00",
                'finishtime' => '13:40',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/radio/tsuchida/',
                'mailaddress'        => 'heso＠1242.com'
            ],
            [
                'program_name'       => 'ENTERTAINMENT NEXT！',
                'dir_name'           => 'lfrmikiko',
                'day_id'        => 7,
                'starttime'  => "13:40",
                'finishtime' => '14:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/mikiko/',
                'mailaddress'        => 'next@1242.com'
            ],
            [
                'program_name'       => '戸田恵子　オトナクオリティ',
                'dir_name'           => 'lfrotokuri',
                'day_id'        => 7,
                'starttime'  => "14:00",
                'finishtime' => '14:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/otokuri/',
                'mailaddress'        => 'toda@1242.com'
            ],
            [
                'program_name'       => '笑福亭鶴瓶　日曜日のそれ',
                'dir_name'           => 'lfrtsurube',
                'day_id'        => 7,
                'starttime'  => "16:00",
                'finishtime' => '17:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/tsurube/',
                'mailaddress'        => 'tsurube@1242.com'
            ],
            [
                'program_name'       => 'サンドウィッチマンの東北魂',
                'dir_name'           => 'lfrsand',
                'day_id'        => 7,
                'starttime'  => "17:30",
                'finishtime' => '17:40',
                'broadcast_id'       => 3,
                'timezone_id'        => 3,
                'officialsite'       => 'https://www.1242.com/sand/',
                'mailaddress'        => 'sand@1242.com'
            ],
            [
                'program_name'       => '渡部陽一 明日へ喝！',
                'dir_name'           => 'lfrwatanabe',
                'day_id'        => 7,
                'starttime'  => "18:00",
                'finishtime' => '18:50',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/watanabe/',
                'mailaddress'        => 'watanabe@1242.com'
            ],
            [
                'program_name'       => '銀シャリのほくほくマネーラジオ',
                'dir_name'           => 'lfrgaitame',
                'day_id'        => 7,
                'starttime'  => "18:50",
                'finishtime' => '19:20',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/gaitame/',
                'mailaddress'        => 'money@1242.com'
            ],
            [
                'program_name'       => 'OBP☆ただいま進化中!',
                'dir_name'           => 'lfrobp',
                'day_id'        => 7,
                'starttime'  => "19:20",
                'finishtime' => '19:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.allnightnippon.com/obp/',
                'mailaddress'        => 'obp@allnightnippon.com'
            ],
            [
                'program_name'       => '玉城ティナとある世界',
                'dir_name'           => 'lfrtina',
                'day_id'        => 7,
                'starttime'  => "20:30",
                'finishtime' => '20:50',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/tina/',
                'mailaddress'        => 'tina@1242.com'
            ],
            [
                'program_name'       => '刀剣乱舞2.5ラジオ',
                'dir_name'           => 'lfrtouken',
                'day_id'        => 7,
                'starttime'  => "20:50",
                'finishtime' => '21:10',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.allnightnippon.com/touken2_5/',
                'mailaddress'        => 'touken2_5@1242.com'
            ],
            [
                'program_name'       => 'すとぷりのStop Listen!',
                'dir_name'           => 'lfrstpr',
                'day_id'        => 7,
                'starttime'  => "21:10",
                'finishtime' => '21:20',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/stpr/',
                'mailaddress'        => 'stpr@1242.com'
            ],
            [
                'program_name'       => 'MANKAI STAGE『A3!』ラジオ',
                'dir_name'           => 'lfrmsa3',
                'day_id'        => 7,
                'starttime'  => "21:20",
                'finishtime' => '21:40',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.allnightnippon.com/msa3/',
                'mailaddress'        => 'msa3@allnightnippon.com'
            ],
            [
                'program_name'       => '浦井健治のDressing Room',
                'dir_name'           => 'lfrurai',
                'day_id'        => 7,
                'starttime'  => "21:40",
                'finishtime' => '22:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/urai/',
                'mailaddress'        => 'urai@1242.com'
            ],
            [
                'program_name'       => 'ももいろクローバーＺ　ももクロくらぶxoxo',
                'dir_name'           => 'lfrmomoclo',
                'day_id'        => 7,
                'starttime'  => "22:00",
                'finishtime' => '22:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.allnightnippon.com/momoclo/',
                'mailaddress'        => 'momoclo@allnightnippon.com'
            ],
            [
                'program_name'       => '高橋みなみと朝井リョウ ヨブンのこと',
                'dir_name'           => 'lfryobunnokoto',
                'day_id'        => 7,
                'starttime'  => "22:30",
                'finishtime' => '23:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.allnightnippon.com/yobunnokoto/',
                'mailaddress'        => 'yobun@allnightnippon.com'
            ],
            [
                'program_name'       => '#みちょパラ',
                'dir_name'           => 'lfrmichopa',
                'day_id'        => 7,
                'starttime'  => "23:00",
                'finishtime' => '23:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.1242.com/michopa/',
                'mailaddress'        => 'michopa@1242.com'
            ],
            [
                'program_name'       => '欅坂46 こちら有楽町星空放送局',
                'dir_name'           => 'lfrkeyaki',
                'day_id'        => 7,
                'starttime'  => "23:30",
                'finishtime' => '24:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.allnightnippon.com/keyaki/',
                'mailaddress'        => 'keyaki@allnightnippon.com'
            ],
            [
                'program_name'       => 'AKB48 2029ラジオ～10年後の君へ',
                'dir_name'           => 'lfrakb',
                'day_id'        => 7,
                'starttime'  => "24:00",
                'finishtime' => '24:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 5,
                'officialsite'       => '',
                'mailaddress'        => 'akb@allnightnippon.com'
            ],
            [
                'program_name'       => '神田莉緒香のKANDAFUL RADIO',
                'dir_name'           => 'lfrkandaful',
                'day_id'        => 7,
                'starttime'  => "24:30",
                'finishtime' => '24:50',
                'broadcast_id'       => 3,
                'timezone_id'        => 4,
                'officialsite'       => 'https://www.allnightnippon.com/kandaful/',
                'mailaddress'        => 'kandari@allnightnippon.com'
            ],
            [
                'program_name'       => '週刊 なるほど!ニッポン',
                'dir_name'           => 'lfrharenosuke',
                'day_id'        => 7,
                'starttime'  => "24:50",
                'finishtime' => '25:00',
                'broadcast_id'       => 3,
                'timezone_id'        => 5,
                'officialsite'       => 'https://www.1242.com/harenosuke/',
                'mailaddress'        => 'hare@1242.com'
            ],
            [
                'program_name'       => 'max matsuura 仕事が遊びで遊びが仕事',
                'dir_name'           => 'lfrmax',
                'day_id'        => 7,
                'starttime'  => "25:00",
                'finishtime' => '25:30',
                'broadcast_id'       => 3,
                'timezone_id'        => 5,
                'officialsite'       => 'https://www.allnightnippon.com/max/',
                'mailaddress'        => 'max@allnightnippon.com'
            ],
        ];
        $this->programs_model->insert($data);
    }
}

